steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag'
  - '$_IMAGE_NAME'
  - '--cache-from'
  - '$_IMAGE_NAME:latest'
  - '--build-arg'
  - 'BUILDKIT_INLINE_CACHE=1'
  - '.'
  env:
  - 'DOCKER_BUILDKIT=1'

images:
- '$_IMAGE_NAME'

options:
  machineType: 'E2_HIGHCPU_8'  # Faster build machine
  diskSizeGb: 100
  env:
    - 'DOCKER_BUILDKIT=1'

timeout: 1200s  # 20 minutes max (default is 10)
